language: java

# we test at Ubuntu Trusty (Ubuntu 14.04 LTS)
# see https://docs.travis-ci.com/user/trusty-ci-environment/
# This environment is continuously updated as described in https://docs.travis-ci.com/user/build-environment-updates/
dist: trusty
sudo: required

services:
  - postgresql
  - mysql
  - docker

env:
  global:
    - GRADLE_OPTS=-Dorg.gradle.daemon=false
    - TERM=dumb
  matrix:
    - TEST_SUITE=check OPTIONS=modernizer
    - TEST_SUITE=fetcherTest
    - TEST_SUITE=databaseTest
    - TEST_SUITE=guiTest
    - TEST_SUITE=checkstyle

matrix:
    fast_finish: true
    allow_failures:
      - env: TEST_SUITE=fetcherTest

# JavaFX localization tests need a running X environment
before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-add-repository -y ppa:snappy-dev/tools
  - sudo apt-get -qq update
  - sudo apt-get install -y snapcraft
  - "export DISPLAY=:99.0"

install: true

before_script:
  - psql -c 'create database jabref;' -U postgres
  - mysql -u root -e 'create database jabref'

script:
  # --scan enables the Gradle build scan, which can be used to investiage the time each action consumes
  # For more information see https://gradle.com/scans/get-started
  - if [ "$TEST_SUITE" != "guiTest" ] && [ "$TEST_SUITE" != "checkstyle" ]; then ./gradlew $TEST_SUITE $OPTIONS --scan; fi
  - if [ "$TEST_SUITE" == "checkstyle" ]; then ./gradlew checkstyleMain checkstyleTest checkstyleJmh; fi
  - if [ "$TEST_SUITE" == "guiTest" ]; then ./buildres/gui-tests.sh; fi

after_success:
  # enable codecov report
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - openssl aes-256-cbc -K $encrypted_5f91cda8b19d_key -iv $encrypted_5f91cda8b19d_iv -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
  - if [ "$TRAVIS_BRANCH" == "snapcraft" ] && [ "$TEST_SUITE" == "checkstyle" ]; then docker run -v $(pwd):$(pwd) -t ubuntu:xenial sh -c "apt update -qq && apt install snapcraft -y && cd $(pwd) && LANG=C.UTF-8 LC_ALL=C.UTF-8 snapcraft && LANG=C.UTF-8 LC_ALL=C.UTF-8 snapcraft push *.snap --release edge"; fi

after_failure:
  # show test results if build fails
  - $TRAVIS_BUILD_DIR/scripts/after-failure.sh

# cache gradle dependencies
# https://docs.travis-ci.com/user/languages/java#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
